### ISSUE TITLE
[Planning] `@carbon/spec` v0.1

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/spec#1]
Using this as an umbrella issue to launch discussions for a design system specification for Carbon.

**Comment by scottnath** [comment]
These seem like straightforward items to test for:

* is the final HTML correct?
* are the classNames all included and in the right place?
* if given content XYZ does the component return HTML that conforms to that content (ie - are a components conditionals all working as expected?)

**Comment by seejamescode** [comment]
So this sounds like using a testing framework to make sure the right HTML is output?

**Comment by scottnath** [comment]
correct. We'll also want to have functional tests to make sure any associated user-interactions work as expected. We might also consider visual regression tests.

**Comment by joshblack** [comment]
@seejamescode the output will be a testing utility, most likely, but I think we can use this to also discuss the work that would go into that.

I think the goal for the testing utility would be to give someone a scenario, and potentially a series a user actions, and then run those and validate that the output from the framework/library matches what we believe the markup should be (as @scottnath described).

I think another part of this is figuring out the semantic markup for the components, and potentially using this as a place to consolidate the shared UX, content model, etc that derives from these components.

For example, a definition list in HTML is often represented as a "Property Sheet", or something similarly named. This property sheet could be rendered in a variety of platforms, and also requires a different kind of spacing mode (e.g. condensed) so that components nested inside of it adhere to its spacing model.

I think this stuff can be very dense, and very challenging, but would be worthwhile to start putting some of these hard earned lessons from all of our teams somewhere so that it's documented.
